# db-pod.yml
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: db
  name: db
spec:
  containers:
  - image: postgres
    name: db
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cloudsql-db-credentials
          key: password
    - name: POSTGRES_DB
      value: project_development
    - name: PGDATA
      value: /var/lib/postgresql/data
    ports:
    - name: pg
      containerPort: 5432
      hostPort: 5432