# web-controller.yml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/rails-quibbler/rails-quibbler
        env:
          - name: POSTGRES_PASSWORD
            value: alohomora
          - name: POSTGRES_USER
            value: postgres
        name: web
        command: ["foreman", "start", "-f", "Procfile.dev", "-p", "3000"]
        ports:
        - containerPort: 3000
          name: http-server