version: '3.2'
services:
  setup:
    build: .
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    command: "bin/rails db:migrate"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=alohomora
      - POSTGRES_DB=project_development
      - PGDATA=/var/lib/postgresql/data
  db_data:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    command: foreman start -f Procfile.dev -p 3000
    volumes:
      - .:/project
      - type: tmpfs
        target: /project/tmp/pids/
    ports:
      - "3000:3000"
    depends_on:
      - db